const SET_SELECTED_GUESTS = 'reservation/SET_SELECTED_GUESTS';
const SET_SELECTED_CHECK_IN = 'reservation/SET_SELECTED_CHECK_IN';
const SET_SELECTED_CHECK_OUT = 'reservation/SET_SELECTED_CHECK_OUT';
const SET_NUM_NIGHTS = 'reservation/SET_NUM_NIGHTS';
const SET_SELECTED_HOSTING = 'reservation/SET_SELECTED_HOSTING';
const RESET_SELECTED_RESERVATION = 'reservation/RESET_SELECTED_RESERVATION';
const FETCH_USER_RESERVATIONS_ASYNC = 'reservation/FETCH_USER_RESERVATIONS_ASYNC';
const DELETE_USER_RESERVATION_ASYNC = 'reservation/DELETE_USER_RESERVATION_ASYNC';
const CREATE_RESERVATION_ASYNC = 'reservation/CREATE_RESERVATION_ASYNC';

export const RESERVATION_ACTION_TYPES = {
  SET_SELECTED_GUESTS,
  SET_SELECTED_CHECK_IN,
  SET_SELECTED_CHECK_OUT,
  SET_NUM_NIGHTS,
  RESET_SELECTED_RESERVATION,
  SET_SELECTED_HOSTING,
  FETCH_USER_RESERVATIONS_ASYNC,
  DELETE_USER_RESERVATION_ASYNC,
  CREATE_RESERVATION_ASYNC,
};
