const FETCH_PROPERTIES_ASYNC = 'property/FETCH_PROPERTIES_ASYNC';
const FETCH_USER_PROPERTIES_ASYNC = 'property/FETCH_USER_PROPERTIES_ASYNC';
const FETCH_PROPERTIES_BY_CATEGORY_ASYNC = 'property/FETCH_PROPERTIES_BY_CATEGORY_ASYNC';
const FETCH_SELECTED_PROPERTY_ASYNC = 'property/FETCH_SELECTED_PROPERTY_ASYNC';

export const PROPERTY_ACTION_TYPES = {
  FETCH_PROPERTIES_ASYNC,
  FETCH_USER_PROPERTIES_ASYNC,
  FETCH_PROPERTIES_BY_CATEGORY_ASYNC,
  FETCH_SELECTED_PROPERTY_ASYNC,
};
