const FETCH_PROPERTIES_ASYNC = 'property/FETCH_PROPERTIES_ASYNC';
const FETCH_PROPERTIES_BY_CATEGORY_ASYNC = 'property/FETCH_PROPERTIES_BY_CATEGORY_ASYNC';

export const PROPERTY_ACTION_TYPES = {
  FETCH_PROPERTIES_ASYNC,
  FETCH_PROPERTIES_BY_CATEGORY_ASYNC,
};
